// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BillingPaymentMethodSetup : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The hosted checkout URL while the setup is pending</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckoutUrl { get; set; }
#nullable restore
#else
        public string CheckoutUrl { get; set; }
#endif
        /// <summary>When the setup completed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompletedAt { get; set; }
#nullable restore
#else
        public string CompletedAt { get; set; }
#endif
        /// <summary>The failure message when the setup failed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>When the pending setup expires</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpiresAt { get; set; }
#nullable restore
#else
        public string ExpiresAt { get; set; }
#endif
        /// <summary>When the setup failed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailedAt { get; set; }
#nullable restore
#else
        public string FailedAt { get; set; }
#endif
        /// <summary>The billing payment method setup ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The setup state</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetupState? State { get; set; }
        /// <summary>The resource type</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetupType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetup"/> and sets the default values.
        /// </summary>
        public BillingPaymentMethodSetup()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetup"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetup CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetup();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checkout_url", n => { CheckoutUrl = n.GetStringValue(); } },
                { "completed_at", n => { CompletedAt = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetStringValue(); } },
                { "failed_at", n => { FailedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetupState>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetupType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("checkout_url", CheckoutUrl);
            writer.WriteStringValue("completed_at", CompletedAt);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("expires_at", ExpiresAt);
            writer.WriteStringValue("failed_at", FailedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetupState>("state", State);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.BillingPaymentMethodSetupType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
