// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ClusterSizeSku : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The architecture of the cluster SKU (null, x86_64 or arm64)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Architecture { get; set; }
#nullable restore
#else
        public string Architecture { get; set; }
#endif
        /// <summary>The number of CPUs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cpu { get; set; }
#nullable restore
#else
        public string Cpu { get; set; }
#endif
        /// <summary>The recommended Neki router size for the cluster SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultNekiRouter { get; set; }
#nullable restore
#else
        public string DefaultNekiRouter { get; set; }
#endif
        /// <summary>The default Neki router rate for the cluster SKU</summary>
        public double? DefaultNekiRouterRate { get; set; }
        /// <summary>The default vtgate size for the cluster SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultVtgate { get; set; }
#nullable restore
#else
        public string DefaultVtgate { get; set; }
#endif
        /// <summary>The default vtgate rate for the cluster SKU</summary>
        public double? DefaultVtgateRate { get; set; }
        /// <summary>Whether or not the cluster SKU is a development SKU</summary>
        public bool? Development { get; set; }
        /// <summary>The display name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>Whether or not the cluster SKU is enabled for the organization</summary>
        public bool? Enabled { get; set; }
        /// <summary>Whether or not the cluster SKU is for an external keyspace</summary>
        public bool? External { get; set; }
        /// <summary>Whether or not the cluster SKU is Metal</summary>
        public bool? Metal { get; set; }
        /// <summary>The name of the cluster SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Whether or not the cluster SKU is a production SKU</summary>
        public bool? Production { get; set; }
        /// <summary>The provider of the cluster SKU (nil, AWS or GCP)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Provider { get; set; }
#nullable restore
#else
        public string Provider { get; set; }
#endif
        /// <summary>The amount of memory in bytes</summary>
        public int? Ram { get; set; }
        /// <summary>The rate for the cluster SKU</summary>
        public double? Rate { get; set; }
        /// <summary>The replica rate for the cluster SKU</summary>
        public double? ReplicaRate { get; set; }
        /// <summary>The sort order of the cluster SKU</summary>
        public int? SortOrder { get; set; }
        /// <summary>The amount of storage in bytes</summary>
        public int? Storage { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.ClusterSizeSku"/> and sets the default values.
        /// </summary>
        public ClusterSizeSku()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.ClusterSizeSku"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.ClusterSizeSku CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.ClusterSizeSku();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "architecture", n => { Architecture = n.GetStringValue(); } },
                { "cpu", n => { Cpu = n.GetStringValue(); } },
                { "default_neki_router", n => { DefaultNekiRouter = n.GetStringValue(); } },
                { "default_neki_router_rate", n => { DefaultNekiRouterRate = n.GetDoubleValue(); } },
                { "default_vtgate", n => { DefaultVtgate = n.GetStringValue(); } },
                { "default_vtgate_rate", n => { DefaultVtgateRate = n.GetDoubleValue(); } },
                { "development", n => { Development = n.GetBoolValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "external", n => { External = n.GetBoolValue(); } },
                { "metal", n => { Metal = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "production", n => { Production = n.GetBoolValue(); } },
                { "provider", n => { Provider = n.GetStringValue(); } },
                { "ram", n => { Ram = n.GetIntValue(); } },
                { "rate", n => { Rate = n.GetDoubleValue(); } },
                { "replica_rate", n => { ReplicaRate = n.GetDoubleValue(); } },
                { "sort_order", n => { SortOrder = n.GetIntValue(); } },
                { "storage", n => { Storage = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("architecture", Architecture);
            writer.WriteStringValue("cpu", Cpu);
            writer.WriteStringValue("default_neki_router", DefaultNekiRouter);
            writer.WriteDoubleValue("default_neki_router_rate", DefaultNekiRouterRate);
            writer.WriteStringValue("default_vtgate", DefaultVtgate);
            writer.WriteDoubleValue("default_vtgate_rate", DefaultVtgateRate);
            writer.WriteBoolValue("development", Development);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("external", External);
            writer.WriteBoolValue("metal", Metal);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("production", Production);
            writer.WriteStringValue("provider", Provider);
            writer.WriteIntValue("ram", Ram);
            writer.WriteDoubleValue("rate", Rate);
            writer.WriteDoubleValue("replica_rate", ReplicaRate);
            writer.WriteIntValue("sort_order", SortOrder);
            writer.WriteIntValue("storage", Storage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
