// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The behavior when DDL changes during the workflow</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateWorkflowRequestOnDdl
    {
        [EnumMember(Value = "IGNORE")]
        #pragma warning disable CS1591
        Ignore,
        #pragma warning restore CS1591
        [EnumMember(Value = "STOP")]
        #pragma warning disable CS1591
        Stop,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXEC")]
        #pragma warning disable CS1591
        Exec,
        #pragma warning restore CS1591
        [EnumMember(Value = "EXEC_IGNORE")]
        #pragma warning disable CS1591
        ExecIgnore,
        #pragma warning restore CS1591
    }
}
