// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The component to configure: `vttablet` or `mysqld`</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateKeyspaceConfigChangeRequestRequestChangeType
    {
        [EnumMember(Value = "mysqld")]
        #pragma warning disable CS1591
        Mysqld,
        #pragma warning restore CS1591
        [EnumMember(Value = "vttablet")]
        #pragma warning disable CS1591
        Vttablet,
        #pragma warning restore CS1591
    }
}
