// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateBackupPolicyRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The unit for the frequency of the backup policy</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestFrequencyUnit? FrequencyUnit { get; set; }
        /// <summary>A number value for the frequency of the backup policy</summary>
        public int? FrequencyValue { get; set; }
        /// <summary>The name of the backup policy</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The unit for the retention period of the backup policy</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestRetentionUnit? RetentionUnit { get; set; }
        /// <summary>A number value for the retention period of the backup policy</summary>
        public int? RetentionValue { get; set; }
        /// <summary>Day of the week that the backup is scheduled. 0 is Sunday, 6 is Saturday</summary>
        public int? ScheduleDay { get; set; }
        /// <summary>The time of day that the backup is scheduled, in HH:MM format</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduleTime { get; set; }
#nullable restore
#else
        public string ScheduleTime { get; set; }
#endif
        /// <summary>Week of the month that the backup is scheduled. 0 is the first week, 3 is the fourth week</summary>
        public int? ScheduleWeek { get; set; }
        /// <summary>Whether the policy is for production or development branches</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestTarget? Target { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequest"/> and sets the default values.
        /// </summary>
        public CreateBackupPolicyRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "frequency_unit", n => { FrequencyUnit = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestFrequencyUnit>(); } },
                { "frequency_value", n => { FrequencyValue = n.GetIntValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "retention_unit", n => { RetentionUnit = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestRetentionUnit>(); } },
                { "retention_value", n => { RetentionValue = n.GetIntValue(); } },
                { "schedule_day", n => { ScheduleDay = n.GetIntValue(); } },
                { "schedule_time", n => { ScheduleTime = n.GetStringValue(); } },
                { "schedule_week", n => { ScheduleWeek = n.GetIntValue(); } },
                { "target", n => { Target = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestTarget>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestFrequencyUnit>("frequency_unit", FrequencyUnit);
            writer.WriteIntValue("frequency_value", FrequencyValue);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestRetentionUnit>("retention_unit", RetentionUnit);
            writer.WriteIntValue("retention_value", RetentionValue);
            writer.WriteIntValue("schedule_day", ScheduleDay);
            writer.WriteStringValue("schedule_time", ScheduleTime);
            writer.WriteIntValue("schedule_week", ScheduleWeek);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.CreateBackupPolicyRequestTarget>("target", Target);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
