// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The role for the password</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DatabaseBranchPasswordRole
    {
        [EnumMember(Value = "reader")]
        #pragma warning disable CS1591
        Reader,
        #pragma warning restore CS1591
        [EnumMember(Value = "writer")]
        #pragma warning disable CS1591
        Writer,
        #pragma warning restore CS1591
        [EnumMember(Value = "admin")]
        #pragma warning disable CS1591
        Admin,
        #pragma warning restore CS1591
        [EnumMember(Value = "readwriter")]
        #pragma warning disable CS1591
        Readwriter,
        #pragma warning restore CS1591
    }
}
