// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetBranchMetricsMetricsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "avg_parallel_workers")]
        #pragma warning disable CS1591
        AvgParallelWorkers,
        #pragma warning restore CS1591
        [EnumMember(Value = "avg_shard_queries")]
        #pragma warning disable CS1591
        AvgShardQueries,
        #pragma warning restore CS1591
        [EnumMember(Value = "block_cache_hit_ratio")]
        #pragma warning disable CS1591
        BlockCacheHitRatio,
        #pragma warning restore CS1591
        [EnumMember(Value = "blocks_dirtied")]
        #pragma warning disable CS1591
        BlocksDirtied,
        #pragma warning restore CS1591
        [EnumMember(Value = "blocks_hit")]
        #pragma warning disable CS1591
        BlocksHit,
        #pragma warning restore CS1591
        [EnumMember(Value = "blocks_read")]
        #pragma warning disable CS1591
        BlocksRead,
        #pragma warning restore CS1591
        [EnumMember(Value = "blocks_written")]
        #pragma warning disable CS1591
        BlocksWritten,
        #pragma warning restore CS1591
        [EnumMember(Value = "connections")]
        #pragma warning disable CS1591
        Connections,
        #pragma warning restore CS1591
        [EnumMember(Value = "cpu_duration_millis")]
        #pragma warning disable CS1591
        CpuDurationMillis,
        #pragma warning restore CS1591
        [EnumMember(Value = "egress_bytes")]
        #pragma warning disable CS1591
        EgressBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "egress_bytes_per_query")]
        #pragma warning disable CS1591
        EgressBytesPerQuery,
        #pragma warning restore CS1591
        [EnumMember(Value = "ingress_bytes")]
        #pragma warning disable CS1591
        IngressBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "ingress_bytes_per_query")]
        #pragma warning disable CS1591
        IngressBytesPerQuery,
        #pragma warning restore CS1591
        [EnumMember(Value = "io_duration_millis")]
        #pragma warning disable CS1591
        IoDurationMillis,
        #pragma warning restore CS1591
        [EnumMember(Value = "latency_max")]
        #pragma warning disable CS1591
        LatencyMax,
        #pragma warning restore CS1591
        [EnumMember(Value = "latency_p50")]
        #pragma warning disable CS1591
        LatencyP50,
        #pragma warning restore CS1591
        [EnumMember(Value = "latency_p95")]
        #pragma warning disable CS1591
        LatencyP95,
        #pragma warning restore CS1591
        [EnumMember(Value = "latency_p99")]
        #pragma warning disable CS1591
        LatencyP99,
        #pragma warning restore CS1591
        [EnumMember(Value = "latency_p999")]
        #pragma warning disable CS1591
        LatencyP999,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_egress_bytes")]
        #pragma warning disable CS1591
        MaxEgressBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_ingress_bytes")]
        #pragma warning disable CS1591
        MaxIngressBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "max_shard_queries")]
        #pragma warning disable CS1591
        MaxShardQueries,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_dedicated_pgbouncer_cpu_usage")]
        #pragma warning disable CS1591
        PlanetscaleDedicatedPgbouncerCpuUsage,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_dedicated_pgbouncer_current_connections")]
        #pragma warning disable CS1591
        PlanetscaleDedicatedPgbouncerCurrentConnections,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_dedicated_pgbouncer_memory_usage")]
        #pragma warning disable CS1591
        PlanetscaleDedicatedPgbouncerMemoryUsage,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_edge_bytes_received")]
        #pragma warning disable CS1591
        PlanetscaleEdgeBytesReceived,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_edge_bytes_received_rate")]
        #pragma warning disable CS1591
        PlanetscaleEdgeBytesReceivedRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_edge_bytes_sent")]
        #pragma warning disable CS1591
        PlanetscaleEdgeBytesSent,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_edge_bytes_sent_rate")]
        #pragma warning disable CS1591
        PlanetscaleEdgeBytesSentRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_pods_container_ooms")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterPodsContainerOoms,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_pods_container_restarts")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterPodsContainerRestarts,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_pods_container_waiting_reason")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterPodsContainerWaitingReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_pods_cpu_util_percentages")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterPodsCpuUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_pods_mem_util_percentages")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterPodsMemUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_pods_status_phase")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterPodsStatusPhase,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_queries")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueries,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_errors")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryErrors,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_latency_avg")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryLatencyAvg,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_latency_avg_by_database")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryLatencyAvgByDatabase,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_latency_p50")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryLatencyP50,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_latency_p50_by_database")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryLatencyP50ByDatabase,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_latency_p95")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryLatencyP95,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_latency_p95_by_database")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryLatencyP95ByDatabase,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_latency_p99")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryLatencyP99,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_neki_router_query_latency_p99_by_database")]
        #pragma warning disable CS1591
        PlanetscaleNekiRouterQueryLatencyP99ByDatabase,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pgbouncer_current_connections")]
        #pragma warning disable CS1591
        PlanetscalePgbouncerCurrentConnections,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pgbouncer_pools_client")]
        #pragma warning disable CS1591
        PlanetscalePgbouncerPoolsClient,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pgbouncer_pools_server")]
        #pragma warning disable CS1591
        PlanetscalePgbouncerPoolsServer,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pods_container_ooms")]
        #pragma warning disable CS1591
        PlanetscalePodsContainerOoms,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pods_container_restarts")]
        #pragma warning disable CS1591
        PlanetscalePodsContainerRestarts,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pods_container_waiting_reason")]
        #pragma warning disable CS1591
        PlanetscalePodsContainerWaitingReason,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pods_cpu_util_percentages")]
        #pragma warning disable CS1591
        PlanetscalePodsCpuUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pods_iops_total")]
        #pragma warning disable CS1591
        PlanetscalePodsIopsTotal,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_pods_mem_util_percentages")]
        #pragma warning disable CS1591
        PlanetscalePodsMemUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_memory_active_cache_bytes")]
        #pragma warning disable CS1591
        PlanetscalePrimaryMemoryActiveCacheBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_memory_inactive_cache_bytes")]
        #pragma warning disable CS1591
        PlanetscalePrimaryMemoryInactiveCacheBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_memory_mmap_bytes")]
        #pragma warning disable CS1591
        PlanetscalePrimaryMemoryMmapBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_memory_rss_bytes")]
        #pragma warning disable CS1591
        PlanetscalePrimaryMemoryRssBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_pgbouncer_cpu_util_percentages")]
        #pragma warning disable CS1591
        PlanetscalePrimaryPgbouncerCpuUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_pgbouncer_mem_util_percentages")]
        #pragma warning disable CS1591
        PlanetscalePrimaryPgbouncerMemUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_pods_cpu_util_percentages")]
        #pragma warning disable CS1591
        PlanetscalePrimaryPodsCpuUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_pods_iops_total")]
        #pragma warning disable CS1591
        PlanetscalePrimaryPodsIopsTotal,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_pods_mem_util_percentages")]
        #pragma warning disable CS1591
        PlanetscalePrimaryPodsMemUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_pods_status_phase")]
        #pragma warning disable CS1591
        PlanetscalePrimaryPodsStatusPhase,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_postgres_connection_state")]
        #pragma warning disable CS1591
        PlanetscalePrimaryPostgresConnectionState,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_postgres_locks")]
        #pragma warning disable CS1591
        PlanetscalePrimaryPostgresLocks,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_storage_usage")]
        #pragma warning disable CS1591
        PlanetscalePrimaryStorageUsage,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_storage_usage_bytes")]
        #pragma warning disable CS1591
        PlanetscalePrimaryStorageUsageBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_volume_usage_percentages")]
        #pragma warning disable CS1591
        PlanetscalePrimaryVolumeUsagePercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_primary_xact_commit_rate")]
        #pragma warning disable CS1591
        PlanetscalePrimaryXactCommitRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_lag_seconds")]
        #pragma warning disable CS1591
        PlanetscaleReplicaLagSeconds,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_memory_active_cache_bytes")]
        #pragma warning disable CS1591
        PlanetscaleReplicaMemoryActiveCacheBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_memory_inactive_cache_bytes")]
        #pragma warning disable CS1591
        PlanetscaleReplicaMemoryInactiveCacheBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_memory_mmap_bytes")]
        #pragma warning disable CS1591
        PlanetscaleReplicaMemoryMmapBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_memory_rss_bytes")]
        #pragma warning disable CS1591
        PlanetscaleReplicaMemoryRssBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_pgbouncer_cpu_util_percentages")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPgbouncerCpuUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_pgbouncer_current_connections")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPgbouncerCurrentConnections,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_pgbouncer_mem_util_percentages")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPgbouncerMemUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_pods_cpu_util_percentages")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPodsCpuUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_pods_iops_total")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPodsIopsTotal,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_pods_mem_util_percentages")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPodsMemUtilPercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_pods_status_phase")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPodsStatusPhase,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_postgres_connection_state")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPostgresConnectionState,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_postgres_locks")]
        #pragma warning disable CS1591
        PlanetscaleReplicaPostgresLocks,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_storage_usage_bytes")]
        #pragma warning disable CS1591
        PlanetscaleReplicaStorageUsageBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replica_volume_usage_percentages")]
        #pragma warning disable CS1591
        PlanetscaleReplicaVolumeUsagePercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replication_slot_max_wal_retained_bytes")]
        #pragma warning disable CS1591
        PlanetscaleReplicationSlotMaxWalRetainedBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_replication_slots_lost")]
        #pragma warning disable CS1591
        PlanetscaleReplicationSlotsLost,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_settings_max_slot_wal_keep_size_bytes")]
        #pragma warning disable CS1591
        PlanetscaleSettingsMaxSlotWalKeepSizeBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_storage_usage_bytes")]
        #pragma warning disable CS1591
        PlanetscaleStorageUsageBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_volume_usage_percentages")]
        #pragma warning disable CS1591
        PlanetscaleVolumeUsagePercentages,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_wal_archiver_failed_rate")]
        #pragma warning disable CS1591
        PlanetscaleWalArchiverFailedRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_wal_archiver_lag_bytes")]
        #pragma warning disable CS1591
        PlanetscaleWalArchiverLagBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_wal_archiver_last_age_succeeded")]
        #pragma warning disable CS1591
        PlanetscaleWalArchiverLastAgeSucceeded,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_wal_archiver_succeeded_rate")]
        #pragma warning disable CS1591
        PlanetscaleWalArchiverSucceededRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "planetscale_wal_size_bytes")]
        #pragma warning disable CS1591
        PlanetscaleWalSizeBytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "queries")]
        #pragma warning disable CS1591
        Queries,
        #pragma warning restore CS1591
        [EnumMember(Value = "query_errors")]
        #pragma warning disable CS1591
        QueryErrors,
        #pragma warning restore CS1591
        [EnumMember(Value = "rows_affected_per_query")]
        #pragma warning disable CS1591
        RowsAffectedPerQuery,
        #pragma warning restore CS1591
        [EnumMember(Value = "rows_read")]
        #pragma warning disable CS1591
        RowsRead,
        #pragma warning restore CS1591
        [EnumMember(Value = "rows_read_per_query")]
        #pragma warning disable CS1591
        RowsReadPerQuery,
        #pragma warning restore CS1591
        [EnumMember(Value = "rows_read_per_returned")]
        #pragma warning disable CS1591
        RowsReadPerReturned,
        #pragma warning restore CS1591
        [EnumMember(Value = "rows_returned")]
        #pragma warning disable CS1591
        RowsReturned,
        #pragma warning restore CS1591
        [EnumMember(Value = "rows_returned_per_query")]
        #pragma warning disable CS1591
        RowsReturnedPerQuery,
        #pragma warning restore CS1591
        [EnumMember(Value = "rows_written")]
        #pragma warning disable CS1591
        RowsWritten,
        #pragma warning restore CS1591
        [EnumMember(Value = "storage_per_table")]
        #pragma warning disable CS1591
        StoragePerTable,
        #pragma warning restore CS1591
        [EnumMember(Value = "total_duration_millis")]
        #pragma warning disable CS1591
        TotalDurationMillis,
        #pragma warning restore CS1591
        [EnumMember(Value = "traffic_control_throttled")]
        #pragma warning disable CS1591
        TrafficControlThrottled,
        #pragma warning restore CS1591
        [EnumMember(Value = "traffic_control_warnings")]
        #pragma warning disable CS1591
        TrafficControlWarnings,
        #pragma warning restore CS1591
        [EnumMember(Value = "violations")]
        #pragma warning disable CS1591
        Violations,
        #pragma warning restore CS1591
        [EnumMember(Value = "vtgate_cpu_avg_by_az")]
        #pragma warning disable CS1591
        VtgateCpuAvgByAz,
        #pragma warning restore CS1591
        [EnumMember(Value = "vtgate_cpu_by_az")]
        #pragma warning disable CS1591
        VtgateCpuByAz,
        #pragma warning restore CS1591
        [EnumMember(Value = "vtgate_latency_p50")]
        #pragma warning disable CS1591
        VtgateLatencyP50,
        #pragma warning restore CS1591
        [EnumMember(Value = "vtgate_latency_p95")]
        #pragma warning disable CS1591
        VtgateLatencyP95,
        #pragma warning restore CS1591
        [EnumMember(Value = "vtgate_memory_avg_by_az")]
        #pragma warning disable CS1591
        VtgateMemoryAvgByAz,
        #pragma warning restore CS1591
        [EnumMember(Value = "vtgate_memory_by_az")]
        #pragma warning disable CS1591
        VtgateMemoryByAz,
        #pragma warning restore CS1591
        [EnumMember(Value = "vtgate_requests")]
        #pragma warning disable CS1591
        VtgateRequests,
        #pragma warning restore CS1591
    }
}
