// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetVtctldOperation200Response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The vtctld action being executed, such as move_tables_create</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the operation has reached a terminal state</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Completed { get; set; }
#nullable restore
#else
        public string Completed { get; set; }
#endif
        /// <summary>When the operation completed, or null while it is still running</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompletedAt { get; set; }
#nullable restore
#else
        public string CompletedAt { get; set; }
#endif
        /// <summary>When the operation was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The error message, present when the operation fails or its status could not be checked</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The UUID of the operation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Operation-specific metadata captured when the operation started</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseMetadata Metadata { get; set; }
#endif
        /// <summary>Operation-specific result payload, present once the operation succeeds</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseResult? Result { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseResult Result { get; set; }
#endif
        /// <summary>The current state of the operation</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseState? State { get; set; }
        /// <summary>Timeout in seconds</summary>
        public int? Timeout { get; set; }
        /// <summary>The object type, always VtctldOperation</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200Response"/> and sets the default values.
        /// </summary>
        public GetVtctldOperation200Response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200Response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200Response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200Response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "completed", n => { Completed = n.GetStringValue(); } },
                { "completed_at", n => { CompletedAt = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseMetadata>(global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseMetadata.CreateFromDiscriminatorValue); } },
                { "result", n => { Result = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseResult>(global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseResult.CreateFromDiscriminatorValue); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseState>(); } },
                { "timeout", n => { Timeout = n.GetIntValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteStringValue("completed", Completed);
            writer.WriteStringValue("completed_at", CompletedAt);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseMetadata>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseResult>("result", Result);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.GetVtctldOperation200ResponseState>("state", State);
            writer.WriteIntValue("timeout", Timeout);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
