// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The cadence unit</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InsightsAgentScheduleFrequencyUnit
    {
        [EnumMember(Value = "day")]
        #pragma warning disable CS1591
        Day,
        #pragma warning restore CS1591
        [EnumMember(Value = "week")]
        #pragma warning disable CS1591
        Week,
        #pragma warning restore CS1591
        [EnumMember(Value = "month")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
    }
}
