// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class NekiShardConfigurationProfile : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The architecture of the cluster size SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Architecture { get; set; }
#nullable restore
#else
        public string Architecture { get; set; }
#endif
        /// <summary>The display name of the cluster size SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClusterDisplayName { get; set; }
#nullable restore
#else
        public string ClusterDisplayName { get; set; }
#endif
        /// <summary>The name of the cluster size SKU</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClusterSize { get; set; }
#nullable restore
#else
        public string ClusterSize { get; set; }
#endif
        /// <summary>When the shard configuration profile was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Whether this is the default shard configuration profile</summary>
        public bool? Default { get; set; }
        /// <summary>The ID of the shard configuration profile</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The latest PostgreSQL image available to the shard configuration profile</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LatestPostgresImageVersion { get; set; }
#nullable restore
#else
        public string LatestPostgresImageVersion { get; set; }
#endif
        /// <summary>The latest PostgreSQL minor version available to the shard configuration profile</summary>
        public int? LatestPostgresMinorVersion { get; set; }
        /// <summary>Whether shards using this configuration profile use metal instances</summary>
        public bool? Metal { get; set; }
        /// <summary>The name of the shard configuration profile</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The PostgreSQL image used by the shard configuration profile</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostgresImageVersion { get; set; }
#nullable restore
#else
        public string PostgresImageVersion { get; set; }
#endif
        /// <summary>The PostgreSQL major version used by the shard configuration profile</summary>
        public int? PostgresMajorVersion { get; set; }
        /// <summary>The PostgreSQL minor version used by the shard configuration profile</summary>
        public int? PostgresMinorVersion { get; set; }
        /// <summary>The number of replicas for shards using this configuration profile</summary>
        public int? Replicas { get; set; }
        /// <summary>The number of shards using this configuration profile</summary>
        public int? Shards { get; set; }
        /// <summary>The current state of the shard configuration profile</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfileState? State { get; set; }
        /// <summary>The storage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfileStorage? Storage { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfileStorage Storage { get; set; }
#endif
        /// <summary>When the shard configuration profile was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfile"/> and sets the default values.
        /// </summary>
        public NekiShardConfigurationProfile()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "architecture", n => { Architecture = n.GetStringValue(); } },
                { "cluster_display_name", n => { ClusterDisplayName = n.GetStringValue(); } },
                { "cluster_size", n => { ClusterSize = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "default", n => { Default = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "latest_postgres_image_version", n => { LatestPostgresImageVersion = n.GetStringValue(); } },
                { "latest_postgres_minor_version", n => { LatestPostgresMinorVersion = n.GetIntValue(); } },
                { "metal", n => { Metal = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "postgres_image_version", n => { PostgresImageVersion = n.GetStringValue(); } },
                { "postgres_major_version", n => { PostgresMajorVersion = n.GetIntValue(); } },
                { "postgres_minor_version", n => { PostgresMinorVersion = n.GetIntValue(); } },
                { "replicas", n => { Replicas = n.GetIntValue(); } },
                { "shards", n => { Shards = n.GetIntValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfileState>(); } },
                { "storage", n => { Storage = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfileStorage>(global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfileStorage.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("architecture", Architecture);
            writer.WriteStringValue("cluster_display_name", ClusterDisplayName);
            writer.WriteStringValue("cluster_size", ClusterSize);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteBoolValue("default", Default);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("latest_postgres_image_version", LatestPostgresImageVersion);
            writer.WriteIntValue("latest_postgres_minor_version", LatestPostgresMinorVersion);
            writer.WriteBoolValue("metal", Metal);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("postgres_image_version", PostgresImageVersion);
            writer.WriteIntValue("postgres_major_version", PostgresMajorVersion);
            writer.WriteIntValue("postgres_minor_version", PostgresMinorVersion);
            writer.WriteIntValue("replicas", Replicas);
            writer.WriteIntValue("shards", Shards);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfileState>("state", State);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.NekiShardConfigurationProfileStorage>("storage", Storage);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
