// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The type of the parameter</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum NekiParameterParameterType
    {
        [EnumMember(Value = "array")]
        #pragma warning disable CS1591
        Array,
        #pragma warning restore CS1591
        [EnumMember(Value = "boolean")]
        #pragma warning disable CS1591
        Boolean,
        #pragma warning restore CS1591
        [EnumMember(Value = "bytes")]
        #pragma warning disable CS1591
        Bytes,
        #pragma warning restore CS1591
        [EnumMember(Value = "float")]
        #pragma warning disable CS1591
        FloatValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "integer")]
        #pragma warning disable CS1591
        Integer,
        #pragma warning restore CS1591
        [EnumMember(Value = "select")]
        #pragma warning disable CS1591
        Select,
        #pragma warning restore CS1591
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        StringValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "time")]
        #pragma warning disable CS1591
        Time,
        #pragma warning restore CS1591
    }
}
