// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrganizationTeam : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The analyst_databases property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamAnalystDatabasesItem>? AnalystDatabases { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamAnalystDatabasesItem> AnalystDatabases { get; set; }
#endif
        /// <summary>When the team was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The creator property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamCreator? Creator { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamCreator Creator { get; set; }
#endif
        /// <summary>The databases property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamDatabasesItem>? Databases { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamDatabasesItem> Databases { get; set; }
#endif
        /// <summary>The description of the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The display name of the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DisplayName { get; set; }
#nullable restore
#else
        public string DisplayName { get; set; }
#endif
        /// <summary>The ID of the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether the team is managed through SSO/directory services</summary>
        public bool? Managed { get; set; }
        /// <summary>The members property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamMembersItem>? Members { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamMembersItem> Members { get; set; }
#endif
        /// <summary>The name of the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The slug of the team</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>When the team was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeam"/> and sets the default values.
        /// </summary>
        public OrganizationTeam()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeam"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeam CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeam();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "analyst_databases", n => { AnalystDatabases = n.GetCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamAnalystDatabasesItem>(global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamAnalystDatabasesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "creator", n => { Creator = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamCreator>(global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamCreator.CreateFromDiscriminatorValue); } },
                { "databases", n => { Databases = n.GetCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamDatabasesItem>(global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamDatabasesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "managed", n => { Managed = n.GetBoolValue(); } },
                { "members", n => { Members = n.GetCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamMembersItem>(global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamMembersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamAnalystDatabasesItem>("analyst_databases", AnalystDatabases);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamCreator>("creator", Creator);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamDatabasesItem>("databases", Databases);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("display_name", DisplayName);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("managed", Managed);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.OrganizationTeamMembersItem>("members", Members);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("slug", Slug);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
