// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginatedPostgresBouncerDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemActor? Actor { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemActor Actor { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemBranch? Branch { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemBranch Branch { get; set; }
#endif
        /// <summary>When the bouncer was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>When the bouncer was deleted</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DeletedAt { get; set; }
#nullable restore
#else
        public string DeletedAt { get; set; }
#endif
        /// <summary>The ID of the bouncer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name of the bouncer</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The parameters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemParametersItem>? Parameters { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemParametersItem> Parameters { get; set; }
#endif
        /// <summary>The count of replicas in each cell</summary>
        public int? ReplicasPerCell { get; set; }
        /// <summary>The sku property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemSku? Sku { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemSku Sku { get; set; }
#endif
        /// <summary>The instance type the bouncer targets</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemTarget? Target { get; set; }
        /// <summary>When the bouncer was updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItem"/> and sets the default values.
        /// </summary>
        public PaginatedPostgresBouncerDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actor", n => { Actor = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemActor>(global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemActor.CreateFromDiscriminatorValue); } },
                { "branch", n => { Branch = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemBranch>(global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemBranch.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "deleted_at", n => { DeletedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parameters", n => { Parameters = n.GetCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemParametersItem>(global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemParametersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "replicas_per_cell", n => { ReplicasPerCell = n.GetIntValue(); } },
                { "sku", n => { Sku = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemSku>(global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemSku.CreateFromDiscriminatorValue); } },
                { "target", n => { Target = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemTarget>(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemActor>("actor", Actor);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemBranch>("branch", Branch);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("deleted_at", DeletedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemParametersItem>("parameters", Parameters);
            writer.WriteIntValue("replicas_per_cell", ReplicasPerCell);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemSku>("sku", Sku);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedPostgresBouncerDataItemTarget>("target", Target);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
