// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginatedAuditLogEventDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The action that was taken</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Action { get; set; }
#nullable restore
#else
        public string Action { get; set; }
#endif
        /// <summary>The name of the actor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActorDisplayName { get; set; }
#nullable restore
#else
        public string ActorDisplayName { get; set; }
#endif
        /// <summary>The ID of the actor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActorId { get; set; }
#nullable restore
#else
        public string ActorId { get; set; }
#endif
        /// <summary>The type of the actor. Such as &apos;User&apos; or &apos;ServiceToken&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ActorType { get; set; }
#nullable restore
#else
        public string ActorType { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The name of the auditable object</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuditableDisplayName { get; set; }
#nullable restore
#else
        public string AuditableDisplayName { get; set; }
#endif
        /// <summary>The ID of the auditable object</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuditableId { get; set; }
#nullable restore
#else
        public string AuditableId { get; set; }
#endif
        /// <summary>The type of the auditable. Such as &apos;Organization&apos; or &apos;Database&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuditableType { get; set; }
#nullable restore
#else
        public string AuditableType { get; set; }
#endif
        /// <summary>The action that was taken</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AuditAction { get; set; }
#nullable restore
#else
        public string AuditAction { get; set; }
#endif
        /// <summary>When the audit log was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>The ID for the audit log</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The location of the actor based on their IP address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Location { get; set; }
#nullable restore
#else
        public string Location { get; set; }
#endif
        /// <summary>Additional metadata containing details about the change</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItemMetadataProperty? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItemMetadataProperty Metadata { get; set; }
#endif
        /// <summary>The IP address of the actor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RemoteIp { get; set; }
#nullable restore
#else
        public string RemoteIp { get; set; }
#endif
        /// <summary>The name of the target</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetDisplayName { get; set; }
#nullable restore
#else
        public string TargetDisplayName { get; set; }
#endif
        /// <summary>The ID of the target</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetId { get; set; }
#nullable restore
#else
        public string TargetId { get; set; }
#endif
        /// <summary>The type of the target. Such as &apos;DatabaseBranch&apos; or &apos;DatabaseBranchPassword&apos;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetType { get; set; }
#nullable restore
#else
        public string TargetType { get; set; }
#endif
        /// <summary>When the audit log was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItem"/> and sets the default values.
        /// </summary>
        public PaginatedAuditLogEventDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "action", n => { Action = n.GetStringValue(); } },
                { "actor_display_name", n => { ActorDisplayName = n.GetStringValue(); } },
                { "actor_id", n => { ActorId = n.GetStringValue(); } },
                { "actor_type", n => { ActorType = n.GetStringValue(); } },
                { "audit_action", n => { AuditAction = n.GetStringValue(); } },
                { "auditable_display_name", n => { AuditableDisplayName = n.GetStringValue(); } },
                { "auditable_id", n => { AuditableId = n.GetStringValue(); } },
                { "auditable_type", n => { AuditableType = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItemMetadataProperty>(global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItemMetadataProperty.CreateFromDiscriminatorValue); } },
                { "remote_ip", n => { RemoteIp = n.GetStringValue(); } },
                { "target_display_name", n => { TargetDisplayName = n.GetStringValue(); } },
                { "target_id", n => { TargetId = n.GetStringValue(); } },
                { "target_type", n => { TargetType = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("action", Action);
            writer.WriteStringValue("actor_display_name", ActorDisplayName);
            writer.WriteStringValue("actor_id", ActorId);
            writer.WriteStringValue("actor_type", ActorType);
            writer.WriteStringValue("auditable_display_name", AuditableDisplayName);
            writer.WriteStringValue("auditable_id", AuditableId);
            writer.WriteStringValue("auditable_type", AuditableType);
            writer.WriteStringValue("audit_action", AuditAction);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("location", Location);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedAuditLogEventDataItemMetadataProperty>("metadata", Metadata);
            writer.WriteStringValue("remote_ip", RemoteIp);
            writer.WriteStringValue("target_display_name", TargetDisplayName);
            writer.WriteStringValue("target_id", TargetId);
            writer.WriteStringValue("target_type", TargetType);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
