// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The disk autoscaling strategy</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaginatedDatabaseBranchKeyspaceDataItemDiskAutoscalingStrategy
    {
        [EnumMember(Value = "grow")]
        #pragma warning disable CS1591
        Grow,
        #pragma warning restore CS1591
        [EnumMember(Value = "disable")]
        #pragma warning disable CS1591
        Disable,
        #pragma warning restore CS1591
        [EnumMember(Value = "shrink")]
        #pragma warning disable CS1591
        Shrink,
        #pragma warning restore CS1591
    }
}
