// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>Controls when node TTL drains are allowed</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaginatedDatabaseBranchKeyspaceDataItemNodeTtlStrategy
    {
        [EnumMember(Value = "node_ttl_follow_maintenance")]
        #pragma warning disable CS1591
        NodeTtlFollowMaintenance,
        #pragma warning restore CS1591
        [EnumMember(Value = "node_ttl_always")]
        #pragma warning disable CS1591
        NodeTtlAlways,
        #pragma warning restore CS1591
        [EnumMember(Value = "node_ttl_off")]
        #pragma warning disable CS1591
        NodeTtlOff,
        #pragma warning restore CS1591
    }
}
