// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The subject for the errors</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PaginatedSchemaLintErrorDataItemSubjectType
    {
        [EnumMember(Value = "table_error")]
        #pragma warning disable CS1591
        TableError,
        #pragma warning restore CS1591
        [EnumMember(Value = "vschema_error")]
        #pragma warning disable CS1591
        VschemaError,
        #pragma warning restore CS1591
        [EnumMember(Value = "routing_rules_error")]
        #pragma warning disable CS1591
        RoutingRulesError,
        #pragma warning restore CS1591
    }
}
