// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaginatedOAuthApplicationDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>All available scopes grouped by resource type with scope, description, selected, and admin flags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemAllScopesByResourceProperty? AllScopesByResource { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemAllScopesByResourceProperty AllScopesByResource { get; set; }
#endif
        /// <summary>The image source for the OAuth application&apos;s avatar</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Avatar { get; set; }
#nullable restore
#else
        public string Avatar { get; set; }
#endif
        /// <summary>The OAuth application&apos;s unique client id</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientId { get; set; }
#nullable restore
#else
        public string ClientId { get; set; }
#endif
        /// <summary>When the OAuth application was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>Whether the OAuth application was created via Dynamic Client Registration</summary>
        public bool? Dcr { get; set; }
        /// <summary>The domain of the OAuth application. Used for verification of a valid redirect uri</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Domain { get; set; }
#nullable restore
#else
        public string Domain { get; set; }
#endif
        /// <summary>The ID of the app</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>MCP tool groups (id, label, section, tools, scopes, parent_id, default_enabled, roles) selectable when authorizing a DCR app; only present for DCR apps. Database-section groups also carry org_scopes (the organization-tier scope names granting the group across all databases in an organization) and org_roles (the organization roles allowed to grant them); both are null for organization-section groups</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemMcpToolGroupsItemProperty>? McpToolGroups { get; set; }
#nullable restore
#else
        public List<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemMcpToolGroupsItemProperty> McpToolGroups { get; set; }
#endif
        /// <summary>The name of the app</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The redirect URI of the OAuth application</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RedirectUri { get; set; }
#nullable restore
#else
        public string RedirectUri { get; set; }
#endif
        /// <summary>Whether the OAuth application requires at least one organization to be authorized</summary>
        public bool? RequiresOrgScope { get; set; }
        /// <summary>The scopes that the OAuth application requires on a user account, as a space-separated string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Scopes { get; set; }
#nullable restore
#else
        public string Scopes { get; set; }
#endif
        /// <summary>Scopes grouped by resource type (database, organization, branch, user) with scope, description, and admin flag</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemScopesByResourceProperty? ScopesByResource { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemScopesByResourceProperty ScopesByResource { get; set; }
#endif
        /// <summary>Whether the OAuth application is limited to authorizing a single organization</summary>
        public bool? SingleOrgAuthorization { get; set; }
        /// <summary>The number of tokens issued by the OAuth application</summary>
        public int? Tokens { get; set; }
        /// <summary>When the OAuth application was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItem"/> and sets the default values.
        /// </summary>
        public PaginatedOAuthApplicationDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "all_scopes_by_resource", n => { AllScopesByResource = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemAllScopesByResourceProperty>(global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemAllScopesByResourceProperty.CreateFromDiscriminatorValue); } },
                { "avatar", n => { Avatar = n.GetStringValue(); } },
                { "client_id", n => { ClientId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "dcr", n => { Dcr = n.GetBoolValue(); } },
                { "domain", n => { Domain = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mcp_tool_groups", n => { McpToolGroups = n.GetCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemMcpToolGroupsItemProperty>(global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemMcpToolGroupsItemProperty.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "redirect_uri", n => { RedirectUri = n.GetStringValue(); } },
                { "requires_org_scope", n => { RequiresOrgScope = n.GetBoolValue(); } },
                { "scopes", n => { Scopes = n.GetStringValue(); } },
                { "scopes_by_resource", n => { ScopesByResource = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemScopesByResourceProperty>(global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemScopesByResourceProperty.CreateFromDiscriminatorValue); } },
                { "single_org_authorization", n => { SingleOrgAuthorization = n.GetBoolValue(); } },
                { "tokens", n => { Tokens = n.GetIntValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemAllScopesByResourceProperty>("all_scopes_by_resource", AllScopesByResource);
            writer.WriteStringValue("avatar", Avatar);
            writer.WriteStringValue("client_id", ClientId);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteBoolValue("dcr", Dcr);
            writer.WriteStringValue("domain", Domain);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemMcpToolGroupsItemProperty>("mcp_tool_groups", McpToolGroups);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("redirect_uri", RedirectUri);
            writer.WriteBoolValue("requires_org_scope", RequiresOrgScope);
            writer.WriteStringValue("scopes", Scopes);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.PaginatedOAuthApplicationDataItemScopesByResourceProperty>("scopes_by_resource", ScopesByResource);
            writer.WriteBoolValue("single_org_authorization", SingleOrgAuthorization);
            writer.WriteIntValue("tokens", Tokens);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
