// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The namespace of the parameter</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PgbouncerNamespace
    {
        [EnumMember(Value = "pgbouncer")]
        #pragma warning disable CS1591
        Pgbouncer,
        #pragma warning restore CS1591
    }
}
