// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    /// <summary>The storage type (gp3 or io2)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostgresClusterResizeRequestStorageType
    {
        [EnumMember(Value = "gp3")]
        #pragma warning disable CS1591
        Gp3,
        #pragma warning restore CS1591
        [EnumMember(Value = "io2")]
        #pragma warning disable CS1591
        Io2,
        #pragma warning restore CS1591
        [EnumMember(Value = "pd_ssd")]
        #pragma warning disable CS1591
        PdSsd,
        #pragma warning restore CS1591
        [EnumMember(Value = "hyperdisk_balanced")]
        #pragma warning disable CS1591
        HyperdiskBalanced,
        #pragma warning restore CS1591
        [EnumMember(Value = "premium_v2_lrs")]
        #pragma warning disable CS1591
        PremiumV2Lrs,
        #pragma warning restore CS1591
    }
}
