// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateKeyspaceRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The maximum number of shards rolled out in parallel, from 1 to 32. Set to null to use the infrastructure default of 1.</summary>
        public int? MaxRollout { get; set; }
        /// <summary>The replication_durability_constraints property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestReplicationDurabilityConstraints? ReplicationDurabilityConstraints { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestReplicationDurabilityConstraints ReplicationDurabilityConstraints { get; set; }
#endif
        /// <summary>The throttler property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestThrottler? Throttler { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestThrottler Throttler { get; set; }
#endif
        /// <summary>The vreplication_flags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestVreplicationFlags? VreplicationFlags { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestVreplicationFlags VreplicationFlags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequest"/> and sets the default values.
        /// </summary>
        public UpdateKeyspaceRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "max_rollout", n => { MaxRollout = n.GetIntValue(); } },
                { "replication_durability_constraints", n => { ReplicationDurabilityConstraints = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestReplicationDurabilityConstraints>(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestReplicationDurabilityConstraints.CreateFromDiscriminatorValue); } },
                { "throttler", n => { Throttler = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestThrottler>(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestThrottler.CreateFromDiscriminatorValue); } },
                { "vreplication_flags", n => { VreplicationFlags = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestVreplicationFlags>(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestVreplicationFlags.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("max_rollout", MaxRollout);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestReplicationDurabilityConstraints>("replication_durability_constraints", ReplicationDurabilityConstraints);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestThrottler>("throttler", Throttler);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateKeyspaceRequestVreplicationFlags>("vreplication_flags", VreplicationFlags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
