// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdateReadOnlyReplicaRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The cluster size SKU name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClusterSize { get; set; }
#nullable restore
#else
        public string ClusterSize { get; set; }
#endif
        /// <summary>Configuration parameters nested by namespace (e.g., {&quot;pgconf&quot;: {&quot;max_connections&quot;: &quot;300&quot;}}). Values must be greater than or equal to the primary&apos;s.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestParameters? Parameters { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestParameters Parameters { get; set; }
#endif
        /// <summary>The number of instances serving reads</summary>
        public int? Replicas { get; set; }
        /// <summary>The storage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestStorage? Storage { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestStorage Storage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequest"/> and sets the default values.
        /// </summary>
        public UpdateReadOnlyReplicaRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cluster_size", n => { ClusterSize = n.GetStringValue(); } },
                { "parameters", n => { Parameters = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestParameters>(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestParameters.CreateFromDiscriminatorValue); } },
                { "replicas", n => { Replicas = n.GetIntValue(); } },
                { "storage", n => { Storage = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestStorage>(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestStorage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cluster_size", ClusterSize);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestParameters>("parameters", Parameters);
            writer.WriteIntValue("replicas", Replicas);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateReadOnlyReplicaRequestStorage>("storage", Storage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
