// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Workflow : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The actor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowActor? Actor { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowActor Actor { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The branch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowBranch? Branch { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowBranch Branch { get; set; }
#endif
        /// <summary>When the workflow was cancelled</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CancelledAt { get; set; }
#nullable restore
#else
        public string CancelledAt { get; set; }
#endif
        /// <summary>The cancelled_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCancelledBy? CancelledBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCancelledBy CancelledBy { get; set; }
#endif
        /// <summary>When the workflow was completed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompletedAt { get; set; }
#nullable restore
#else
        public string CompletedAt { get; set; }
#endif
        /// <summary>The completed_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCompletedBy? CompletedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCompletedBy CompletedBy { get; set; }
#endif
        /// <summary>When the workflow was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedAt { get; set; }
#nullable restore
#else
        public string CreatedAt { get; set; }
#endif
        /// <summary>When the cutover was completed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CutoverAt { get; set; }
#nullable restore
#else
        public string CutoverAt { get; set; }
#endif
        /// <summary>The cutover_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCutoverBy? CutoverBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCutoverBy CutoverBy { get; set; }
#endif
        /// <summary>When the data copy was completed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DataCopyCompletedAt { get; set; }
#nullable restore
#else
        public string DataCopyCompletedAt { get; set; }
#endif
        /// <summary>Whether or not secondary keys are deferred</summary>
        public bool? DeferSecondaryKeys { get; set; }
        /// <summary>The global_keyspace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowGlobalKeyspace? GlobalKeyspace { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowGlobalKeyspace GlobalKeyspace { get; set; }
#endif
        /// <summary>The ID of the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Whether or not the workflow may be restarted</summary>
        public bool? MayRestart { get; set; }
        /// <summary>Whether or not the workflow may be retried</summary>
        public bool? MayRetry { get; set; }
        /// <summary>The name of the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The sequence number of the workflow</summary>
        public int? Number { get; set; }
        /// <summary>The behavior when DDL changes during the workflow</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowOnDdl? OnDdl { get; set; }
        /// <summary>Whether or not the primaries have been switched</summary>
        public bool? PrimariesSwitched { get; set; }
        /// <summary>Whether or not the replicas have been switched</summary>
        public bool? ReplicasSwitched { get; set; }
        /// <summary>When the workflow was retried</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RetriedAt { get; set; }
#nullable restore
#else
        public string RetriedAt { get; set; }
#endif
        /// <summary>The retried_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowRetriedBy? RetriedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowRetriedBy RetriedBy { get; set; }
#endif
        /// <summary>When the workflow was reversed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReversedAt { get; set; }
#nullable restore
#else
        public string ReversedAt { get; set; }
#endif
        /// <summary>The reversed_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedBy? ReversedBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedBy ReversedBy { get; set; }
#endif
        /// <summary>The reversed_cutover_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedCutoverBy? ReversedCutoverBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedCutoverBy ReversedCutoverBy { get; set; }
#endif
        /// <summary>Whether or not sequence tables have been created</summary>
        public bool? SequenceTablesApplied { get; set; }
        /// <summary>The source_keyspace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSourceKeyspace? SourceKeyspace { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSourceKeyspace SourceKeyspace { get; set; }
#endif
        /// <summary>When the workflow was started</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>The state of the workflow</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowState? State { get; set; }
        /// <summary>When the primaries were switched</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SwitchPrimariesAt { get; set; }
#nullable restore
#else
        public string SwitchPrimariesAt { get; set; }
#endif
        /// <summary>The switch_primaries_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchPrimariesBy? SwitchPrimariesBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchPrimariesBy SwitchPrimariesBy { get; set; }
#endif
        /// <summary>When the replicas were switched</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SwitchReplicasAt { get; set; }
#nullable restore
#else
        public string SwitchReplicasAt { get; set; }
#endif
        /// <summary>The switch_replicas_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchReplicasBy? SwitchReplicasBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchReplicasBy SwitchReplicasBy { get; set; }
#endif
        /// <summary>The target_keyspace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowTargetKeyspace? TargetKeyspace { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowTargetKeyspace TargetKeyspace { get; set; }
#endif
        /// <summary>When the workflow was last updated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedAt { get; set; }
#nullable restore
#else
        public string UpdatedAt { get; set; }
#endif
        /// <summary>Whether or not the verified data is stale</summary>
        public bool? VerifiedDataStale { get; set; }
        /// <summary>When the data was verified</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VerifyDataAt { get; set; }
#nullable restore
#else
        public string VerifyDataAt { get; set; }
#endif
        /// <summary>The verify_data_by property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowVerifyDataBy? VerifyDataBy { get; set; }
#nullable restore
#else
        public global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowVerifyDataBy VerifyDataBy { get; set; }
#endif
        /// <summary>The errors that occurred during the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowErrors { get; set; }
#nullable restore
#else
        public string WorkflowErrors { get; set; }
#endif
        /// <summary>The subtype of the workflow</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? WorkflowSubtype { get; set; }
#nullable restore
#else
        public string WorkflowSubtype { get; set; }
#endif
        /// <summary>The type of the workflow</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Models.MoveTablesWorkflowType? WorkflowType { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.Workflow"/> and sets the default values.
        /// </summary>
        public Workflow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.Workflow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.PlanetScale.OpenApiClient.Models.Workflow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.PlanetScale.OpenApiClient.Models.Workflow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "actor", n => { Actor = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowActor>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowActor.CreateFromDiscriminatorValue); } },
                { "branch", n => { Branch = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowBranch>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowBranch.CreateFromDiscriminatorValue); } },
                { "cancelled_at", n => { CancelledAt = n.GetStringValue(); } },
                { "cancelled_by", n => { CancelledBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCancelledBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCancelledBy.CreateFromDiscriminatorValue); } },
                { "completed_at", n => { CompletedAt = n.GetStringValue(); } },
                { "completed_by", n => { CompletedBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCompletedBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCompletedBy.CreateFromDiscriminatorValue); } },
                { "created_at", n => { CreatedAt = n.GetStringValue(); } },
                { "cutover_at", n => { CutoverAt = n.GetStringValue(); } },
                { "cutover_by", n => { CutoverBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCutoverBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCutoverBy.CreateFromDiscriminatorValue); } },
                { "data_copy_completed_at", n => { DataCopyCompletedAt = n.GetStringValue(); } },
                { "defer_secondary_keys", n => { DeferSecondaryKeys = n.GetBoolValue(); } },
                { "global_keyspace", n => { GlobalKeyspace = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowGlobalKeyspace>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowGlobalKeyspace.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "may_restart", n => { MayRestart = n.GetBoolValue(); } },
                { "may_retry", n => { MayRetry = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetIntValue(); } },
                { "on_ddl", n => { OnDdl = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowOnDdl>(); } },
                { "primaries_switched", n => { PrimariesSwitched = n.GetBoolValue(); } },
                { "replicas_switched", n => { ReplicasSwitched = n.GetBoolValue(); } },
                { "retried_at", n => { RetriedAt = n.GetStringValue(); } },
                { "retried_by", n => { RetriedBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowRetriedBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowRetriedBy.CreateFromDiscriminatorValue); } },
                { "reversed_at", n => { ReversedAt = n.GetStringValue(); } },
                { "reversed_by", n => { ReversedBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedBy.CreateFromDiscriminatorValue); } },
                { "reversed_cutover_by", n => { ReversedCutoverBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedCutoverBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedCutoverBy.CreateFromDiscriminatorValue); } },
                { "sequence_tables_applied", n => { SequenceTablesApplied = n.GetBoolValue(); } },
                { "source_keyspace", n => { SourceKeyspace = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSourceKeyspace>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSourceKeyspace.CreateFromDiscriminatorValue); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowState>(); } },
                { "switch_primaries_at", n => { SwitchPrimariesAt = n.GetStringValue(); } },
                { "switch_primaries_by", n => { SwitchPrimariesBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchPrimariesBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchPrimariesBy.CreateFromDiscriminatorValue); } },
                { "switch_replicas_at", n => { SwitchReplicasAt = n.GetStringValue(); } },
                { "switch_replicas_by", n => { SwitchReplicasBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchReplicasBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchReplicasBy.CreateFromDiscriminatorValue); } },
                { "target_keyspace", n => { TargetKeyspace = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowTargetKeyspace>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowTargetKeyspace.CreateFromDiscriminatorValue); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
                { "verified_data_stale", n => { VerifiedDataStale = n.GetBoolValue(); } },
                { "verify_data_at", n => { VerifyDataAt = n.GetStringValue(); } },
                { "verify_data_by", n => { VerifyDataBy = n.GetObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowVerifyDataBy>(global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowVerifyDataBy.CreateFromDiscriminatorValue); } },
                { "workflow_errors", n => { WorkflowErrors = n.GetStringValue(); } },
                { "workflow_subtype", n => { WorkflowSubtype = n.GetStringValue(); } },
                { "workflow_type", n => { WorkflowType = n.GetEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.MoveTablesWorkflowType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowActor>("actor", Actor);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowBranch>("branch", Branch);
            writer.WriteStringValue("cancelled_at", CancelledAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCancelledBy>("cancelled_by", CancelledBy);
            writer.WriteStringValue("completed_at", CompletedAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCompletedBy>("completed_by", CompletedBy);
            writer.WriteStringValue("created_at", CreatedAt);
            writer.WriteStringValue("cutover_at", CutoverAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowCutoverBy>("cutover_by", CutoverBy);
            writer.WriteStringValue("data_copy_completed_at", DataCopyCompletedAt);
            writer.WriteBoolValue("defer_secondary_keys", DeferSecondaryKeys);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowGlobalKeyspace>("global_keyspace", GlobalKeyspace);
            writer.WriteStringValue("id", Id);
            writer.WriteBoolValue("may_restart", MayRestart);
            writer.WriteBoolValue("may_retry", MayRetry);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("number", Number);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowOnDdl>("on_ddl", OnDdl);
            writer.WriteBoolValue("primaries_switched", PrimariesSwitched);
            writer.WriteBoolValue("replicas_switched", ReplicasSwitched);
            writer.WriteStringValue("retried_at", RetriedAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowRetriedBy>("retried_by", RetriedBy);
            writer.WriteStringValue("reversed_at", ReversedAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedBy>("reversed_by", ReversedBy);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowReversedCutoverBy>("reversed_cutover_by", ReversedCutoverBy);
            writer.WriteBoolValue("sequence_tables_applied", SequenceTablesApplied);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSourceKeyspace>("source_keyspace", SourceKeyspace);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowState>("state", State);
            writer.WriteStringValue("switch_primaries_at", SwitchPrimariesAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchPrimariesBy>("switch_primaries_by", SwitchPrimariesBy);
            writer.WriteStringValue("switch_replicas_at", SwitchReplicasAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowSwitchReplicasBy>("switch_replicas_by", SwitchReplicasBy);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowTargetKeyspace>("target_keyspace", TargetKeyspace);
            writer.WriteStringValue("updated_at", UpdatedAt);
            writer.WriteBoolValue("verified_data_stale", VerifiedDataStale);
            writer.WriteStringValue("verify_data_at", VerifyDataAt);
            writer.WriteObjectValue<global::Soenneker.PlanetScale.OpenApiClient.Models.WorkflowVerifyDataBy>("verify_data_by", VerifyDataBy);
            writer.WriteStringValue("workflow_errors", WorkflowErrors);
            writer.WriteStringValue("workflow_subtype", WorkflowSubtype);
            writer.WriteEnumValue<global::Soenneker.PlanetScale.OpenApiClient.Models.MoveTablesWorkflowType>("workflow_type", WorkflowType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
