// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.PlanetScale.OpenApiClient.Models;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.AuditLog;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Billing;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.ClusterSizeSkus;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Databases;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Invoices;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Members;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.OauthApplications;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Regions;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.ServiceTokens;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Sso;
using Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Teams;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.PlanetScale.OpenApiClient.Organizations.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \organizations\{organization}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithOrganizationItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The auditLog property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.AuditLog.AuditLogRequestBuilder AuditLog
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.AuditLog.AuditLogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The billing property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Billing.BillingRequestBuilder Billing
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Billing.BillingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The clusterSizeSkus property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.ClusterSizeSkus.ClusterSizeSkusRequestBuilder ClusterSizeSkus
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.ClusterSizeSkus.ClusterSizeSkusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The databases property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Databases.DatabasesRequestBuilder Databases
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Databases.DatabasesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invoices property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Invoices.InvoicesRequestBuilder Invoices
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Invoices.InvoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The members property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Members.MembersRequestBuilder Members
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Members.MembersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauthApplications property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.OauthApplications.OauthApplicationsRequestBuilder OauthApplications
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.OauthApplications.OauthApplicationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The regions property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Regions.RegionsRequestBuilder Regions
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Regions.RegionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The serviceTokens property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.ServiceTokens.ServiceTokensRequestBuilder ServiceTokens
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.ServiceTokens.ServiceTokensRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sso property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Sso.SsoRequestBuilder Sso
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Sso.SsoRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Teams.TeamsRequestBuilder Teams
        {
            get => new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganizationItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organization}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithOrganizationItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/organizations/{organization}", rawUrl)
        {
        }
        /// <summary>
        /// ### AuthorizationA service token or OAuth token must have at least one of the following access or scopes in order to use this API endpoint:**Service Token Accesses** `read_organization`**OAuth Scopes** | Resource | Scopes || :------- | :---------- || User | `read_organizations` || Organization | `read_organization` |
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.Organization"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PlanetScale.OpenApiClient.Models.Organization?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PlanetScale.OpenApiClient.Models.Organization> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.PlanetScale.OpenApiClient.Models.Organization>(requestInfo, global::Soenneker.PlanetScale.OpenApiClient.Models.Organization.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ### AuthorizationA   OAuth token must have at least one of the following   scopes in order to use this API endpoint:**OAuth Scopes** | Resource | Scopes || :------- | :---------- || Organization | `write_organization` |
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Models.Organization"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.PlanetScale.OpenApiClient.Models.Organization?> PatchAsync(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.PlanetScale.OpenApiClient.Models.Organization> PatchAsync(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.Organization500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.PlanetScale.OpenApiClient.Models.Organization>(requestInfo, global::Soenneker.PlanetScale.OpenApiClient.Models.Organization.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// ### AuthorizationA service token or OAuth token must have at least one of the following access or scopes in order to use this API endpoint:**Service Token Accesses** `read_organization`**OAuth Scopes** | Resource | Scopes || :------- | :---------- || User | `read_organizations` || Organization | `read_organization` |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// ### AuthorizationA   OAuth token must have at least one of the following   scopes in order to use this API endpoint:**OAuth Scopes** | Resource | Scopes || :------- | :---------- || Organization | `write_organization` |
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.PlanetScale.OpenApiClient.Models.UpdateOrganizationRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.PlanetScale.OpenApiClient.Organizations.Item.WithOrganizationItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
